config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  resources :places
  resources :users, only:[:index,:show,:create,:new]
  resources :comments

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def create
    Comment.create(content: params[:comment],user_id: session[:user_id],place_id:params[:id])
    redirect_to(:back)
  end

  def show
   @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find_by(params[:id])
  end

  def destroy
    Comment.destroy(params['id'])
    redirect_to(:back)
  end

  def update
    @comment = params['comment']
    Comment.update( params[:id],
                  content: @comment['content'])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @places = Place.all.reverse
    gon.places = Place.limit(20)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
skip_before_filter  :verify_authenticity_token
# this code allowed me to skip an error that said, "Can't verify CSRF token authenticity."
before_filter :authorize

  def index
    @places = Place.where(user_id: session[:user_id]).reverse
    gon.places = Place.limit(10)
  end

  def create
    @place = params['place']
    Place.create(name: @place['name'],
                  address: @place['address'],
                  latitude: @place['latitude'],
                  longitude: @place['longitude'],
                  user_id: session[:user_id])
    redirect_to("/places")
  end

  def edit
    @place = Place.find(params[:id])
  end

  def destroy
    Place.destroy(params['id'])
    redirect_to(:back)
  end

  def show
    @place = Place.find_by(id: params[:id])
    @comment  = Comment.where(place_id: params[:id])
  end

  def update
    @place = params['place']
    Place.update( params[:id],
                  name: @place['name'],
                  address: @place['address'],
                  latitude: @place['latitude'],
                  longitude: @place['longitude'],
                  user_id: session[:user_id])

    redirect_to("/places")
  end

  # def place_params
  #   params(:place).permit(:name, :address, :latitude, :longitude)
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
   user = User.find_by_email(params[:email])
   # If the user exists AND the password entered is correct.
   if user && user.authenticate(params[:password])
     # Save the user id inside the browser cookie. This is how we keep the user
     # logged in when they navigate around our website.
     session[:user_id] = user.id
     redirect_to '/'
   else
   # If user's login doesn't work, send them back to the login form.
     redirect_to '/login'
   end
 end

 def destroy
   session[:user_id] = nil
   redirect_to '/'
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
    end

    def create
      user = User.new(user_params)
      if user.save
        session[:user_id] = user.id
        redirect_to '/'
      else
        redirect_to '/signup'
      end
    end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= render 'layouts/header' %>
        <h1 class="center recs-header">GA Students Recommendations</h1>

    <div class="row">
        <!-- SCSS styling not working had to use inline. -->
        <div style =  "padding-bottom: 40px;" class="col s6 ">
            <input id="pac-input" class="controls" type="text" placeholder="Enter a location">
            <div class="map-responsive" id="map"></div>
        </div>
        <p id="notice"><%= notice %></p>

        <br>
        <div class="col s6">
            <div class="card-panel dation">
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th colspan="3"></th>
                            <th>Address</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @places.each do |place| %>
                        <tr>
                            <td><%= place.name %></td>
                            <th colspan="3"></th>
                            <td><%= place.address %></td>
                            <th colspan="3"></th>
                            <td><%= link_to 'Details', place %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>

<%= render 'layouts/footer' %>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBAchzUgA7nscKvpxt3v_YoC1pn5_55GcM&libraries=places&callback=initMap" async defer></script>

app/views/layouts/_footer.html.erb
<footer class="page-footer clearfix grey darken-4">
    <div class="container">
        <div class="row">
          <div class="col l6 s12">
                <h5 class="grey-text text-darken-1">GA Lunch Break</h5>
                <p class="grey-text text-darken-1">Immersives go by fast. Don’t waste your time eating crappy food!</p>
                <p class="grey-text text-darken-1">© 2016 Copyright Skulder | Made with &hearts;</p>
          </div>
          <div class="col l4 offset-l1 s11">
                <h5 class="grey-text text-darken-1">Contributors:</h5>
                <ul>
                  <li><a class="grey-text text-darken-1" target="_blank" href="https://github.com/ayalalaura">Laura A | </a></li>
                  <li><a class="grey-text text-darken-1" target="_blank" href="https://github.com/mcabz27">Matthew C | </a></li>
                  <li><a class="grey-text text-darken-1" target="_blank" href="https://github.com/JennRC87">Jennfer C | </a></li>
                  <li><a class="grey-text text-darken-1" target="_blank" href="https://github.com/itajenglish">Taj E | </a></li>
                  <li><a class="grey-text text-darken-1" target="_blank" href="https://github.com/jayanzaman">Jayan Z | </a></li>
                </ul>
              </div>
            </div>
          </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="black">
    <div class="nav-wrapper">
     <a href="/" class="brand-logo"><%= image_tag("galb_white.png", size: "125x52", alt: "GA Lunch Break") %></a>
     <ul class="right hide-on-med-and-down">
          <% if current_user %>
            <li><span class="header-username">Signed in as <%= current_user.name %></span></li>
            <li><a class="header-tab" href="/">Home</a></li>
            <li><a class="header-tab" href="/places">My Places</a></li>
            <li><%= link_to "Logout", '/logout', class: "header-tab" %></li>
          <% else %>
            <li><%= link_to 'Login', '/login', class: "header-tab" %></li> <li><%= link_to 'Sign Up', '/signup', class: "header-tab" %></li>
          <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>GALunchBreakApp</title>
        <%= csrf_meta_tags %>
        <%= include_gon %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body class="background_bw">
        <%= yield %>

    </body>




</html>

app/views/places/_form.html.erb
<%= form_for(place) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<%= render 'footer' %>
<% end %>

app/views/places/edit.html.erb
<%= render 'layouts/header' %>
<div class="edit-place">
  <h2>Editing Places</h2>

  <%= form_for @place do |c| %>

  <%= c.label :name %><br>
  <%= c.text_field :name %><br>

  <%= c.label :address %><br>
  <%= c.text_field :address %><br>

  <%= c.label :latitude %><br>
  <%= c.text_field :latitude %><br>

  <%= c.label :longitude %><br>
  <%= c.text_field :longitude %><br>

  <% hidden_field(:place, :id) %>
    <%= c.submit "Update", class: "btn waves-effect waves-light red accent-4 edit-btn"%>
  <% end %>
</div>

<%= render 'layouts/footer' %>

app/views/places/index.html.erb
<%= render 'layouts/header' %>

    <div class="row">
        <div class="col s6">
            <input id="pac-input" class="controls" type="text" placeholder="Enter a location">
            <div class="map-responsive" id="map"></div>
        </div>
        <p id="notice"><%= notice %></p>
        <div class="col s6">
            <div class="card-panel">
                <%= form_for :place, method: 'create', url: {action: "create"} do |f| %>
                <%= label(:place, :name) %><br>
                <%= f.text_field :name %><br>
                <%= label(:place, :address) %><br>
                <%= f.text_field :address %><br>
                <%= label(:place, :latitude) %><br>
                <%= f.text_field :latitude %><br>
                <%= label(:place, :longitude) %><br>
                <%= f.text_field :longitude %><br>
                <br>
                <%= f.submit "Save" %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="container recs">
        <div class="col s12">
            <div class="card-panel">
                <h1>Your Recommendations</h1>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th colspan="3"></th>
                            <th>Address</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @places.each do |place| %>
                        <tr>
                            <td><%= place.name %></td>
                            <th colspan="3"></th>
                            <td><%= place.address %></td>
                            <th colspan="3"></th>
                            <td><%= link_to 'Details', place %></td>
                            <td><%= link_to 'Edit', edit_place_path(place) %></td>
                            <td><%= link_to 'Delete', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br>

<%= render 'layouts/footer' %>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBAchzUgA7nscKvpxt3v_YoC1pn5_55GcM&libraries=places&callback=initMap" async defer></script>

app/views/places/new.html.erb
<%= form_for :place, method: 'create', url: {action: "create"} do |f| %>
<%= render "layouts/header" %>

<%= label(:place, :name) %><br>
<%= f.text_field :name %><br>
<%= label(:place, :address) %><br>
<%= f.text_field :address %><br>
<%= label(:place, :latitude) %><br>
<%= f.text_field :latitude %><br>
<%= label(:place, :longitude) %><br>
<%= f.text_field :longitude %><br>
<br>
<%= f.submit "Save This Place" %>
<% end %>

<%= render "layouts/footer" %>

app/views/places/show.html.erb
<%= render 'layouts/header' %>
<div class="delete-place">
 <!--  <h2>One Place at a Time, Bruh!</h2> -->
  <h3>Name: <%= @place.name %></h3>
  <ul>
    <h4><li>Address: <%= @place.address %></li></h4>
    <h4><li>Latitude: <%= @place.latitude %></li></h4>
    <h4><li>Longitude: <%= @place.longitude %></li></h4>
  </ul>
  <br>

  <h3>Comments</h3>
  <% @comment.each do |c| %>
    <ul>
      <li><%= c.content %></li><%= link_to "Delete Comment", comment_path(c.id), method: :delete, data: {id: c.id, confirm: "Are you sure you want to delete this?"} %>
    </ul>

  <% end %>
  <br>
  <%= form_tag(controller: "comments", method: "POST") do %>
    <%= label_tag(:comment, "Comment On Your Experiece") %>
    <%= text_field_tag(:comment) %>
    <%= hidden_field_tag('id', @place.id) %>
    <%= submit_tag "Comment", class: "btn waves-effect waves-light red accent-4 edit-btn" %>
  <% end %>
</div>
<%= render 'layouts/footer' %>

app/views/users/new.html.erb
<%= render 'layouts/header' %>
<main>
  <div class="container signup-form z-depth-2">
    <div class="col s8 offset-s2">
      <h3 class="form-headers">SIGN UP</h3>

       <%= form_for :user, url: '/users' do |f| %>
        <h5>Name:</h5> <%= f.text_field :name %> <br>
        <h5>Email:</h5> <%= f.text_field :email %> <br>
        <h5>Password:</h5> <%= f.password_field :password %> <br>
        <h5>Password Confirmation:</h5> <%= f.password_field :password_confirmation %>
      <%= f.submit "Sign Up", class: "btn waves-effect waves-light red accent-4"%>
      <% end %>
    </div>
  </div>
</main>
<%= render 'layouts/footer' %>